# Generated by Django 3.0.4 on 2023-09-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='ownere',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='message',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
